[package]
name = "bbs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
askama = "0.12.0"
serde = "1.0.188"
serde_derive = "1.0.188"
sled = "0.34.7"

